# Generated by Django 6.0.5 on 2026-05-27 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sources",
                    models.CharField(
                        choices=[
                            ("sap", "SAP"),
                            ("utility", "Utility"),
                            ("navan", "Navan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="ingestion_files/"
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("row_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestions",
                        to="core.client",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                ("row_index", models.IntegerField()),
                ("raw_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="core.client",
                    ),
                ),
                (
                    "ingestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="ingestion.ingestion",
                    ),
                ),
            ],
            options={
                "ordering": ["ingestion", "row_index"],
            },
        ),
        migrations.CreateModel(
            name="NormalizedRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                ("transaction_id", models.CharField(blank=True, max_length=50)),
                ("transaction_date", models.DateField(blank=True, null=True)),
                ("vendor_name", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("description", models.TextField(blank=True)),
                ("sap_po_number", models.CharField(blank=True, max_length=50)),
                ("sap_cost_center", models.CharField(blank=True, max_length=20)),
                ("sap_gl_account", models.CharField(blank=True, max_length=20)),
                ("sap_company_code", models.CharField(blank=True, max_length=10)),
                ("sap_material_group", models.CharField(blank=True, max_length=20)),
                ("utility_account_number", models.CharField(blank=True, max_length=50)),
                ("utility_meter_id", models.CharField(blank=True, max_length=50)),
                ("utility_service_type", models.CharField(blank=True, max_length=50)),
                (
                    "utility_usage_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "utility_billing_period_start",
                    models.DateField(blank=True, null=True),
                ),
                ("utility_billing_period_end", models.DateField(blank=True, null=True)),
                ("navan_trip_id", models.CharField(blank=True, max_length=100)),
                ("navan_traveler_name", models.CharField(blank=True, max_length=255)),
                ("navan_traveler_email", models.CharField(blank=True, max_length=255)),
                ("navan_travel_type", models.CharField(blank=True, max_length=50)),
                ("navan_departure_date", models.DateField(blank=True, null=True)),
                ("navan_return_date", models.DateField(blank=True, null=True)),
                ("navan_origin", models.CharField(blank=True, max_length=10)),
                ("navan_destination", models.CharField(blank=True, max_length=10)),
                ("navan_policy_compliant", models.BooleanField(null=True)),
                ("navan_out_of_policy_reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("flagged", "Flagged"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("normalization_warnings", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_records",
                        to="core.client",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raw_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_record",
                        to="ingestion.rawrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ingestion",
            index=models.Index(
                fields=["client", "sources", "status"],
                name="ingestion_i_client__6e582b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawrecord",
            index=models.Index(
                fields=["client", "source"], name="ingestion_r_client__0f0201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawrecord",
            index=models.Index(
                fields=["ingestion", "row_index"], name="ingestion_r_ingesti_ce2885_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(
                fields=["client", "source", "status"],
                name="ingestion_n_client__b39d79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(
                fields=["client", "transaction_date"],
                name="ingestion_n_client__c300eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedrecord",
            index=models.Index(
                fields=["client", "vendor_name"], name="ingestion_n_client__4f76f2_idx"
            ),
        ),
    ]
